name: expensium
description: "A new Flutter project."

publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.4
  cloud_firestore: ^5.4.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  uuid: ^4.5.0
  workmanager: ^0.5.2

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/decrease.png
    - assets/images/increase.png
    - assets/images/home_screen.png
    - assets/images/money.png
    - assets/images/home.png
    - assets/images/settings.png
    - assets/images/empty.png
    - assets/images/neutral.png
    - assets/images/logo.png
    - lib/presentation/animations/green-arrow.json
    - lib/presentation/animations/red-arrow.json
    - lib/presentation/animations/delete.json

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Black.ttf
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
        - asset: assets/fonts/WorkSans-SemiBold.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Light.ttf
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/WorkSans-Thin.ttf
